### ISSUE TITLE
No support for xbox/psn

### ISSUE THREAD

**Issue by LawlyPopz** [sdwolfe32/ovrstat#1]
https://ovrstat.com/v1/stats/xbl/us/LittleJediWolf Does not want to work :(

**Comment by sdwolfe32** [comment]
Hey Lawly, I just updated the API to handle xbl and psn stat requests. The URL you posted should now work. Let me know if you have any other questions or issues.

**Comment by LawlyPopz** [comment]
Aweosme your are amazing <3
