### ISSUE TITLE
overwatchGuid0x086000000000052a in CompetitiveStats.CareerStats["allHeroes"].Miscellaneous

### ISSUE THREAD

**Issue by L11R** [sdwolfe32/ovrstat#13]

**Comment by sdwolfe32** [comment]
I don't know what this means. Please provide me a detailed description so I can take care of it.

**Comment by L11R** [comment]
@sdwolfe32 
I got strange field in Miscellaneous. I can't find it on playoverwatch.com. 
![image](https://user-images.githubusercontent.com/5345489/32047359-5ac5da7c-ba4e-11e7-8966-7c3d906b59b1.png)
