### ISSUE TITLE
Website down??

### ISSUE THREAD

**Issue by LawlyPopz** [sdwolfe32/ovrstat#2]
this is the only way to contact you but seems like the websites down :(

**Comment by LawlyPopz** [comment]
Back up now :)

**Comment by sdwolfe32** [comment]
I was pushing an update that fixes the key on All Heros. Sorry for the downtime. Just wanted to make sure it was working the right way for you! On Fri, Jul 22, 2016 at 6:13 PM, Wayne < notifications@github.com [notifications@github.com] > wrote:
this is the only way to contact you but seems like the websites down :(

**Comment by LawlyPopz** [comment]
Working like a pro thanks <3  http://api.lawlypopzz.xyz/overwatch/setup.php this is what im making with it for twitch <3

**Comment by sdwolfe32** [comment]
Cool stuff man! Like I said if you have any other issues don't hesitate to post an issue. I'll do my best to respond to them as soon as possible and will work on preventing downtime in the future!
