### ISSUE TITLE
PRESTIGE MISSING

### ISSUE THREAD

**Issue by LawlyPopz** [sdwolfe32/ovrstat#3]
Hey if you check the .player-level class on https://playoverwatch.com below is the PRESTIGE levels for the style="background-image:" would be nice if you could add the Prestige before Level in the json

the Prestige is part of the levelIcon like the link below!
(EG: https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/0x0250000000000918_Border.png)

    # Bronze 0 - 5
    "0x0250000000000918": 0,
    "0x0250000000000919": 0,
    "0x025000000000091A": 0,
    "0x025000000000091B": 0,
    "0x025000000000091C": 0,
    "0x025000000000091D": 0,
    "0x025000000000091E": 0,
    "0x025000000000091F": 0,
    "0x0250000000000920": 0,
    "0x0250000000000921": 0,
    "0x0250000000000922": 1,
    "0x0250000000000924": 1,
    "0x0250000000000925": 1,
    "0x0250000000000926": 1,
    "0x025000000000094C": 1,
    "0x0250000000000927": 1,
    "0x0250000000000928": 1,
    "0x0250000000000929": 1,
    "0x025000000000092B": 1,
    "0x0250000000000950": 1,
    "0x025000000000092A": 2,
    "0x025000000000092C": 2,
    "0x0250000000000937": 2,
    "0x025000000000093B": 2,
    "0x0250000000000933": 2,
    "0x0250000000000923": 2,
    "0x0250000000000944": 2,
    "0x0250000000000948": 2,
    "0x025000000000093F": 2,
    "0x0250000000000951": 2,
    "0x025000000000092D": 3,
    "0x0250000000000930": 3,
    "0x0250000000000934": 3,
    "0x0250000000000938": 3,
    "0x0250000000000940": 3,
    "0x0250000000000949": 3,
    "0x0250000000000952": 3,
    "0x025000000000094D": 3,
    "0x0250000000000945": 3,
    "0x025000000000093C": 3,
    "0x025000000000092E": 4,
    "0x0250000000000931": 4,
    "0x0250000000000935": 4,
    "0x025000000000093D": 4,
    "0x0250000000000946": 4,
    "0x025000000000094A": 4,
    "0x0250000000000953": 4,
    "0x025000000000094E": 4,
    "0x0250000000000939": 4,
    "0x0250000000000941": 4,
    "0x025000000000092F": 5,
    "0x0250000000000932": 5,
    "0x025000000000093E": 5,
    "0x0250000000000936": 5,
    "0x025000000000093A": 5,
    "0x0250000000000942": 5,
    "0x0250000000000947": 5,
    "0x025000000000094F": 5,
    "0x025000000000094B": 5,
    "0x0250000000000954": 5,
    # Silver 6 - 11
    "0x0250000000000956": 6,
    "0x025000000000095C": 6,
    "0x025000000000095D": 6,
    "0x025000000000095E": 6,
    "0x025000000000095F": 6,
    "0x0250000000000960": 6,
    "0x0250000000000961": 6,
    "0x0250000000000962": 6,
    "0x0250000000000963": 6,
    "0x0250000000000964": 6,
    "0x0250000000000957": 7,
    "0x0250000000000965": 7,
    "0x0250000000000966": 7,
    "0x0250000000000967": 7,
    "0x0250000000000968": 7,
    "0x0250000000000969": 7,
    "0x025000000000096A": 7,
    "0x025000000000096B": 7,
    "0x025000000000096C": 7,
    "0x025000000000096D": 7,
    "0x0250000000000958": 8,
    "0x025000000000096E": 8,
    "0x025000000000096F": 8,
    "0x0250000000000970": 8,
    "0x0250000000000971": 8,
    "0x0250000000000972": 8,
    "0x0250000000000973": 8,
    "0x0250000000000974": 8,
    "0x0250000000000975": 8,
    "0x0250000000000976": 8,
    "0x0250000000000959": 9,
    "0x0250000000000977": 9,
    "0x0250000000000978": 9,
    "0x0250000000000979": 9,
    "0x025000000000097A": 9,
    "0x025000000000097B": 9,
    "0x025000000000097C": 9,
    "0x025000000000097D": 9,
    "0x025000000000097E": 9,
    "0x025000000000097F": 9,
    "0x025000000000095A": 10,
    "0x0250000000000980": 10,
    "0x0250000000000981": 10,
    "0x0250000000000982": 10,
    "0x0250000000000983": 10,
    "0x0250000000000984": 10,
    "0x0250000000000985": 10,
    "0x0250000000000986": 10,
    "0x0250000000000987": 10,
    "0x0250000000000988": 10,
    "0x025000000000095B": 11,
    "0x0250000000000989": 11,
    "0x025000000000098A": 11,
    "0x025000000000098B": 11,
    "0x025000000000098C": 11,
    "0x025000000000098D": 11,
    "0x025000000000098E": 11,
    "0x025000000000098F": 11,
    "0x0250000000000991": 11,
    "0x0250000000000990": 11,
    # Gold 12 - 17
    "0x0250000000000992": 12,
    "0x0250000000000993": 12,
    "0x0250000000000994": 12,
    "0x0250000000000995": 12,
    "0x0250000000000996": 12,
    "0x0250000000000997": 12,
    "0x0250000000000998": 12,
    "0x0250000000000999": 12,
    "0x025000000000099A": 12,
    "0x025000000000099B": 12

**Comment by LawlyPopz** [comment]
Please let me know if you get this done as for now im doing a work around using the levelIcon and just removeing some of the string then doing an if to check and echo the right number but would be nice if i can get rid of the extra step

**Comment by sdwolfe32** [comment]
I'm working on implementing this now so you don't have to do it on your end. Could you just re-paste ranks gold and greater? It seems as though they were cut off in your original message.

**Comment by LawlyPopz** [comment]
I have only got as far as 12 as i dont know anyone that high of rank yet

**Comment by sdwolfe32** [comment]
Well you did awesome work creating that map. Saved me a lot of time. I'll implement what you have so far and since it will probably be a while until someone is prestiged in gold, we have some time to put in the rest.

**Comment by LawlyPopz** [comment]
Yup will do please do let me know when this is done :)

**Comment by sdwolfe32** [comment]
Should be up now. Let me know if you have any issues.

**Comment by LawlyPopz** [comment]
Works like a Pro omg I love you Kappa
