### ISSUE TITLE
Project closed?

### ISSUE THREAD

**Issue by dbkynd** [sdwolfe32/ovrstat#6]
Have not been getting a response back from your endpoints for some time now? Has this project stopped?

**Comment by sdwolfe32** [comment]
It's not closed I'm just not happy with it and have decided to take down the server. Wasn't hit for days so not worth paying for. Alternatively I can recommend OWAPI which is pretty similar https://github.com/SunDwarf/OWAPI.

**Comment by dbkynd** [comment]
Makes sense. Thanks for the info.
